### PR TITLE
Add text converting to Hexadecimal Converter page

### PR DESCRIPTION
**Pull request by matejos**
Adds an input box for converting from/to text on the Hexadecimal Converter page, so you can easily convert e.g. bytes32 to text

image

Thank you for this awesome tool! :rocket:

### CODE REVIEW

**Comment by matejos** [comment]
@apoorvlathey Hello! It seems to me that you are the main contributor, could you take a look at this please?

**Comment by apoorvlathey** [comment]
Hey, thanks for the contribution. I'll check it out

**Comment by apoorvlathey** [comment]
Hey @matejos what's your Base/Optimism/Arbitrum address? I'm rewarding the contributors with some ETH.
Here's the post: https://x.com/apoorvlathey/status/1791475159054127184

**Comment by matejos** [comment]
Hey there, thank you very much! Just sent you a DM on X :relaxed:

**Pull request merged**
