### PR TITLE
Set the result according to the number of decimals

### PR DESCRIPTION
**Pull request by lourdrivera123**

### CODE REVIEW

**Comment by lourdrivera123** [comment]
This PR is related to https://github.com/swiss-knife-xyz/swiss-knife/issues/5

**Comment by apoorvlathey** [comment]
Thanks for taking the initiative and deciding to contribute to this project!

**Comment by lourdrivera123** [comment]
Made an update, kindly have a look.

**Comment by lourdrivera123** [comment]
Made an update, kindly have a look.

**Comment by apoorvlathey** [comment]
Had to resort to the previous method, because `(1 / token1PerToken0InDecimals)` had to be limited to the desired decimal values.

**Comment by lourdrivera123** [comment]
> Had to resort to the previous method, because `(1 / token1PerToken0InDecimals)` had to be limited to the desired decimal values.

I think that's better, that way you can only ensure that it is only changed on the display instead of actual calculations.

**Pull request merged**
